routes/web.php
<?php

use App\Http\Controllers\HomeController;

Route::get('/', [HomeController::class, 'main']);
Route::get('/home', [HomeController::class, 'main']);
Route::get('/tags/{id}', [HomeController::class, 'tags']);
Route::get('/category/{id}', [HomeController::class, 'category']);
Route::get('/page/{id}', [HomeController::class, 'page']);
Route::post('/save_comment', [HomeController::class, 'setComment']);
//Route::get('/contacts', [HomeController::class, 'contacts']);


Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Content Category
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tag
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Page
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // Main Carousel
    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
    Route::resource('main-carousels', 'MainCarouselController');

    // Banks
    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
    Route::resource('banks', 'BanksController');

    // Banks Lang
    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
    Route::resource('banks-langs', 'BanksLangController');

    // Language
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // Countries Lang
    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
    Route::resource('countries-langs', 'CountriesLangController');

    // Ref Family Status
    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
    Route::resource('ref-family-statuses', 'RefFamilyStatusController');

    // Ref Family Status Lang
    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');

    // Nationality
    Route::delete('nationalities/destroy', 'NationalityController@massDestroy')->name('nationalities.massDestroy');
    Route::resource('nationalities', 'NationalityController');

    // Nationality Lang
    Route::delete('nationality-langs/destroy', 'NationalityLangController@massDestroy')->name('nationality-langs.massDestroy');
    Route::resource('nationality-langs', 'NationalityLangController');

    // Ref Oked
    Route::delete('ref-okeds/destroy', 'RefOkedController@massDestroy')->name('ref-okeds.massDestroy');
    Route::resource('ref-okeds', 'RefOkedController');

    // Ref Oked Lang
    Route::delete('ref-oked-langs/destroy', 'RefOkedLangController@massDestroy')->name('ref-oked-langs.massDestroy');
    Route::resource('ref-oked-langs', 'RefOkedLangController');

    // Ref Person State
    Route::delete('ref-person-states/destroy', 'RefPersonStateController@massDestroy')->name('ref-person-states.massDestroy');
    Route::resource('ref-person-states', 'RefPersonStateController');

    // Ref Person State Lang
    Route::delete('ref-person-state-langs/destroy', 'RefPersonStateLangController@massDestroy')->name('ref-person-state-langs.massDestroy');
    Route::resource('ref-person-state-langs', 'RefPersonStateLangController');

    // Ref Vacation Types
    Route::delete('ref-vacation-types/destroy', 'RefVacationTypesController@massDestroy')->name('ref-vacation-types.massDestroy');
    Route::resource('ref-vacation-types', 'RefVacationTypesController');

    // Ref Vacation Types Lang
    Route::delete('ref-vacation-types-langs/destroy', 'RefVacationTypesLangController@massDestroy')->name('ref-vacation-types-langs.massDestroy');
    Route::resource('ref-vacation-types-langs', 'RefVacationTypesLangController');

    // Comments
    Route::delete('comments/destroy', 'CommentsController@massDestroy')->name('comments.massDestroy');
    Route::resource('comments', 'CommentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::group(['as' => 'frontend.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
//    Route::get('/home', 'HomeController@index')->name('home');
//
//    // Permissions
//    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
//    Route::resource('permissions', 'PermissionsController');
//
//    // Roles
//    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
//    Route::resource('roles', 'RolesController');
//
//    // Users
//    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
//    Route::resource('users', 'UsersController');
//
//    // Content Category
//    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
//    Route::resource('content-categories', 'ContentCategoryController');
//
//    // Content Tag
//    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
//    Route::resource('content-tags', 'ContentTagController');
//
//    // Content Page
//    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
//    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
//    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
//    Route::resource('content-pages', 'ContentPageController');
//
//    // Main Carousel
//    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
//    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
//    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
//    Route::resource('main-carousels', 'MainCarouselController');
//
//    // Banks
//    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
//    Route::resource('banks', 'BanksController');
//
//    // Banks Lang
//    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
//    Route::resource('banks-langs', 'BanksLangController');
//
//    // Language
//    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
//    Route::resource('languages', 'LanguageController');
//
//    // Countries
//    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
//    Route::resource('countries', 'CountriesController');
//
//    // Countries Lang
//    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
//    Route::resource('countries-langs', 'CountriesLangController');
//
//    // Ref Family Status
//    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
//    Route::resource('ref-family-statuses', 'RefFamilyStatusController');
//
//    // Ref Family Status Lang
//    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
//    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');
//

app/Models/Language.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Language extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'languages';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'name',
        'short',
        'logo',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function languageBanksLangs()
    {
        return $this->hasMany(BanksLang::class, 'language_id', 'id');
    }

    public function languageCountriesLangs()
    {
        return $this->hasMany(CountriesLang::class, 'language_id', 'id');
    }

    public function languageRefFamilyStatusLangs()
    {
        return $this->hasMany(RefFamilyStatusLang::class, 'language_id', 'id');
    }

    public function languageNationalityLangs()
    {
        return $this->hasMany(NationalityLang::class, 'language_id', 'id');
    }

    public function languageRefOkedLangs()
    {
        return $this->hasMany(RefOkedLang::class, 'language_id', 'id');
    }

    public function languageRefPersonStateLangs()
    {
        return $this->hasMany(RefPersonStateLang::class, 'language_id', 'id');
    }

    public function languageRefVacationTypesLangs()
    {
        return $this->hasMany(RefVacationTypesLang::class, 'language_id', 'id');
    }
}

app/Http/Controllers/Admin/LanguageController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyLanguageRequest;
use App\Http\Requests\StoreLanguageRequest;
use App\Http\Requests\UpdateLanguageRequest;
use App\Models\Language;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class LanguageController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('language_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::all();

        return view('admin.languages.index', compact('languages'));
    }

    public function create()
    {
        abort_if(Gate::denies('language_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.languages.create');
    }

    public function store(StoreLanguageRequest $request)
    {
        $language = Language::create($request->all());

        return redirect()->route('admin.languages.index');
    }

    public function edit(Language $language)
    {
        abort_if(Gate::denies('language_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.languages.edit', compact('language'));
    }

    public function update(UpdateLanguageRequest $request, Language $language)
    {
        $language->update($request->all());

        return redirect()->route('admin.languages.index');
    }

    public function show(Language $language)
    {
        abort_if(Gate::denies('language_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $language->load('languageBanksLangs', 'languageCountriesLangs', 'languageRefFamilyStatusLangs', 'languageNationalityLangs', 'languageRefOkedLangs', 'languageRefPersonStateLangs', 'languageRefVacationTypesLangs');

        return view('admin.languages.show', compact('language'));
    }

    public function destroy(Language $language)
    {
        abort_if(Gate::denies('language_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $language->delete();

        return back();
    }

    public function massDestroy(MassDestroyLanguageRequest $request)
    {
        $languages = Language::find(request('ids'));

        foreach ($languages as $language) {
            $language->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/LanguageController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyLanguageRequest;
use App\Http\Requests\StoreLanguageRequest;
use App\Http\Requests\UpdateLanguageRequest;
use App\Models\Language;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class LanguageController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('language_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::all();

        return view('frontend.languages.index', compact('languages'));
    }

    public function create()
    {
        abort_if(Gate::denies('language_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.languages.create');
    }

    public function store(StoreLanguageRequest $request)
    {
        $language = Language::create($request->all());

        return redirect()->route('frontend.languages.index');
    }

    public function edit(Language $language)
    {
        abort_if(Gate::denies('language_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.languages.edit', compact('language'));
    }

    public function update(UpdateLanguageRequest $request, Language $language)
    {
        $language->update($request->all());

        return redirect()->route('frontend.languages.index');
    }

    public function show(Language $language)
    {
        abort_if(Gate::denies('language_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $language->load('languageBanksLangs', 'languageCountriesLangs');

        return view('frontend.languages.show', compact('language'));
    }

    public function destroy(Language $language)
    {
        abort_if(Gate::denies('language_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $language->delete();

        return back();
    }

    public function massDestroy(MassDestroyLanguageRequest $request)
    {
        $languages = Language::find(request('ids'));

        foreach ($languages as $language) {
            $language->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/languages/relationships/languageBanksLangs.blade.php
@can('banks_lang_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.banks-langs.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.banksLang.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.banksLang.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-languageBanksLangs">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.banksLang.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.banksLang.fields.language') }}
                        </th>
                        <th>
                            {{ trans('cruds.banksLang.fields.bank') }}
                        </th>
                        <th>
                            {{ trans('cruds.banksLang.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($banksLangs as $key => $banksLang)
                        <tr data-entry-id="{{ $banksLang->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $banksLang->id ?? '' }}
                            </td>
                            <td>
                                {{ $banksLang->language->name ?? '' }}
                            </td>
                            <td>
                                {{ $banksLang->bank->name ?? '' }}
                            </td>
                            <td>
                                {{ $banksLang->name ?? '' }}
                            </td>
                            <td>
                                @can('banks_lang_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.banks-langs.show', $banksLang->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('banks_lang_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.banks-langs.edit', $banksLang->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('banks_lang_delete')
                                    <form action="{{ route('admin.banks-langs.destroy', $banksLang->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('banks_lang_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.banks-langs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-languageBanksLangs:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/languages/relationships/languageCountriesLangs.blade.php
@can('countries_lang_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.countries-langs.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.countriesLang.title_singular') }}
            </a>
        </div>
    </div>
@endcan

<div class="card">
    <div class="card-header">
        {{ trans('cruds.countriesLang.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-languageCountriesLangs">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.language') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.country') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($countriesLangs as $key => $countriesLang)
                        <tr data-entry-id="{{ $countriesLang->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $countriesLang->id ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->language->name ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->country->name ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->name ?? '' }}
                            </td>
                            <td>
                                @can('countries_lang_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.countries-langs.show', $countriesLang->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('countries_lang_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.countries-langs.edit', $countriesLang->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('countries_lang_delete')
                                    <form action="{{ route('admin.countries-langs.destroy', $countriesLang->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>

@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('countries_lang_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.countries-langs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-languageCountriesLangs:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection