routes/web.php
<?php

use App\Http\Controllers\HomeController;

Route::get('/', [HomeController::class, 'main']);
Route::get('/home', [HomeController::class, 'main']);
Route::get('/tags/{id}', [HomeController::class, 'tags']);
Route::get('/category/{id}', [HomeController::class, 'category']);
Route::get('/page/{id}', [HomeController::class, 'page']);
Route::post('/save_comment', [HomeController::class, 'setComment']);
//Route::get('/contacts', [HomeController::class, 'contacts']);


Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Content Category
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tag
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Page
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // Main Carousel
    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
    Route::resource('main-carousels', 'MainCarouselController');

    // Banks
    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
    Route::resource('banks', 'BanksController');

    // Banks Lang
    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
    Route::resource('banks-langs', 'BanksLangController');

    // Language
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // Countries Lang
    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
    Route::resource('countries-langs', 'CountriesLangController');

    // Ref Family Status
    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
    Route::resource('ref-family-statuses', 'RefFamilyStatusController');

    // Ref Family Status Lang
    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');

    // Nationality
    Route::delete('nationalities/destroy', 'NationalityController@massDestroy')->name('nationalities.massDestroy');
    Route::resource('nationalities', 'NationalityController');

    // Nationality Lang
    Route::delete('nationality-langs/destroy', 'NationalityLangController@massDestroy')->name('nationality-langs.massDestroy');
    Route::resource('nationality-langs', 'NationalityLangController');

    // Ref Oked
    Route::delete('ref-okeds/destroy', 'RefOkedController@massDestroy')->name('ref-okeds.massDestroy');
    Route::resource('ref-okeds', 'RefOkedController');

    // Ref Oked Lang
    Route::delete('ref-oked-langs/destroy', 'RefOkedLangController@massDestroy')->name('ref-oked-langs.massDestroy');
    Route::resource('ref-oked-langs', 'RefOkedLangController');

    // Ref Person State
    Route::delete('ref-person-states/destroy', 'RefPersonStateController@massDestroy')->name('ref-person-states.massDestroy');
    Route::resource('ref-person-states', 'RefPersonStateController');

    // Ref Person State Lang
    Route::delete('ref-person-state-langs/destroy', 'RefPersonStateLangController@massDestroy')->name('ref-person-state-langs.massDestroy');
    Route::resource('ref-person-state-langs', 'RefPersonStateLangController');

    // Ref Vacation Types
    Route::delete('ref-vacation-types/destroy', 'RefVacationTypesController@massDestroy')->name('ref-vacation-types.massDestroy');
    Route::resource('ref-vacation-types', 'RefVacationTypesController');

    // Ref Vacation Types Lang
    Route::delete('ref-vacation-types-langs/destroy', 'RefVacationTypesLangController@massDestroy')->name('ref-vacation-types-langs.massDestroy');
    Route::resource('ref-vacation-types-langs', 'RefVacationTypesLangController');

    // Comments
    Route::delete('comments/destroy', 'CommentsController@massDestroy')->name('comments.massDestroy');
    Route::resource('comments', 'CommentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::group(['as' => 'frontend.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
//    Route::get('/home', 'HomeController@index')->name('home');
//
//    // Permissions
//    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
//    Route::resource('permissions', 'PermissionsController');
//
//    // Roles
//    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
//    Route::resource('roles', 'RolesController');
//
//    // Users
//    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
//    Route::resource('users', 'UsersController');
//
//    // Content Category
//    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
//    Route::resource('content-categories', 'ContentCategoryController');
//
//    // Content Tag
//    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
//    Route::resource('content-tags', 'ContentTagController');
//
//    // Content Page
//    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
//    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
//    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
//    Route::resource('content-pages', 'ContentPageController');
//
//    // Main Carousel
//    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
//    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
//    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
//    Route::resource('main-carousels', 'MainCarouselController');
//
//    // Banks
//    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
//    Route::resource('banks', 'BanksController');
//
//    // Banks Lang
//    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
//    Route::resource('banks-langs', 'BanksLangController');
//
//    // Language
//    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
//    Route::resource('languages', 'LanguageController');
//
//    // Countries
//    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
//    Route::resource('countries', 'CountriesController');
//
//    // Countries Lang
//    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
//    Route::resource('countries-langs', 'CountriesLangController');
//
//    // Ref Family Status
//    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
//    Route::resource('ref-family-statuses', 'RefFamilyStatusController');
//
//    // Ref Family Status Lang
//    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
//    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');
//

app/Models/CountriesLang.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class CountriesLang extends Model
{
    use SoftDeletes, HasFactory;

    public $table = 'countries_langs';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $hidden = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'language_id',
        'country_id',
        'name',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function language()
    {
        return $this->belongsTo(Language::class, 'language_id');
    }

    public function country()
    {
        return $this->belongsTo(Country::class, 'country_id');
    }
}

app/Http/Controllers/Admin/CountriesLangController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCountriesLangRequest;
use App\Http\Requests\StoreCountriesLangRequest;
use App\Http\Requests\UpdateCountriesLangRequest;
use App\Models\CountriesLang;
use App\Models\Country;
use App\Models\Language;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CountriesLangController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('countries_lang_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLangs = CountriesLang::with(['language', 'country'])->get();

        return view('admin.countriesLangs.index', compact('countriesLangs'));
    }

    public function create()
    {
        abort_if(Gate::denies('countries_lang_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countries = Country::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.countriesLangs.create', compact('countries', 'languages'));
    }

    public function store(StoreCountriesLangRequest $request)
    {
        $countriesLang = CountriesLang::create($request->all());

        return redirect()->route('admin.countries-langs.index');
    }

    public function edit(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countries = Country::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countriesLang->load('language', 'country');

        return view('admin.countriesLangs.edit', compact('countries', 'countriesLang', 'languages'));
    }

    public function update(UpdateCountriesLangRequest $request, CountriesLang $countriesLang)
    {
        $countriesLang->update($request->all());

        return redirect()->route('admin.countries-langs.index');
    }

    public function show(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLang->load('language', 'country');

        return view('admin.countriesLangs.show', compact('countriesLang'));
    }

    public function destroy(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLang->delete();

        return back();
    }

    public function massDestroy(MassDestroyCountriesLangRequest $request)
    {
        $countriesLangs = CountriesLang::find(request('ids'));

        foreach ($countriesLangs as $countriesLang) {
            $countriesLang->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/CountriesLangController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyCountriesLangRequest;
use App\Http\Requests\StoreCountriesLangRequest;
use App\Http\Requests\UpdateCountriesLangRequest;
use App\Models\CountriesLang;
use App\Models\Country;
use App\Models\Language;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class CountriesLangController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('countries_lang_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLangs = CountriesLang::with(['language', 'country'])->get();

        return view('frontend.countriesLangs.index', compact('countriesLangs'));
    }

    public function create()
    {
        abort_if(Gate::denies('countries_lang_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countries = Country::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('frontend.countriesLangs.create', compact('countries', 'languages'));
    }

    public function store(StoreCountriesLangRequest $request)
    {
        $countriesLang = CountriesLang::create($request->all());

        return redirect()->route('frontend.countries-langs.index');
    }

    public function edit(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countries = Country::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $countriesLang->load('language', 'country');

        return view('frontend.countriesLangs.edit', compact('countries', 'countriesLang', 'languages'));
    }

    public function update(UpdateCountriesLangRequest $request, CountriesLang $countriesLang)
    {
        $countriesLang->update($request->all());

        return redirect()->route('frontend.countries-langs.index');
    }

    public function show(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLang->load('language', 'country');

        return view('frontend.countriesLangs.show', compact('countriesLang'));
    }

    public function destroy(CountriesLang $countriesLang)
    {
        abort_if(Gate::denies('countries_lang_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $countriesLang->delete();

        return back();
    }

    public function massDestroy(MassDestroyCountriesLangRequest $request)
    {
        $countriesLangs = CountriesLang::find(request('ids'));

        foreach ($countriesLangs as $countriesLang) {
            $countriesLang->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

resources/views/admin/countriesLangs/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.countriesLang.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.countries-langs.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="language_id">{{ trans('cruds.countriesLang.fields.language') }}</label>
                <select class="form-control select2 {{ $errors->has('language') ? 'is-invalid' : '' }}" name="language_id" id="language_id">
                    @foreach($languages as $id => $entry)
                        <option value="{{ $id }}" {{ old('language_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('language'))
                    <div class="invalid-feedback">
                        {{ $errors->first('language') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.language_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="country_id">{{ trans('cruds.countriesLang.fields.country') }}</label>
                <select class="form-control select2 {{ $errors->has('country') ? 'is-invalid' : '' }}" name="country_id" id="country_id">
                    @foreach($countries as $id => $entry)
                        <option value="{{ $id }}" {{ old('country_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('country'))
                    <div class="invalid-feedback">
                        {{ $errors->first('country') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.country_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="name">{{ trans('cruds.countriesLang.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', '') }}">
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/countriesLangs/edit.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.edit') }} {{ trans('cruds.countriesLang.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.countries-langs.update", [$countriesLang->id]) }}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <div class="form-group">
                <label for="language_id">{{ trans('cruds.countriesLang.fields.language') }}</label>
                <select class="form-control select2 {{ $errors->has('language') ? 'is-invalid' : '' }}" name="language_id" id="language_id">
                    @foreach($languages as $id => $entry)
                        <option value="{{ $id }}" {{ (old('language_id') ? old('language_id') : $countriesLang->language->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('language'))
                    <div class="invalid-feedback">
                        {{ $errors->first('language') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.language_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="country_id">{{ trans('cruds.countriesLang.fields.country') }}</label>
                <select class="form-control select2 {{ $errors->has('country') ? 'is-invalid' : '' }}" name="country_id" id="country_id">
                    @foreach($countries as $id => $entry)
                        <option value="{{ $id }}" {{ (old('country_id') ? old('country_id') : $countriesLang->country->id ?? '') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                    @endforeach
                </select>
                @if($errors->has('country'))
                    <div class="invalid-feedback">
                        {{ $errors->first('country') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.country_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="name">{{ trans('cruds.countriesLang.fields.name') }}</label>
                <input class="form-control {{ $errors->has('name') ? 'is-invalid' : '' }}" type="text" name="name" id="name" value="{{ old('name', $countriesLang->name) }}">
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.countriesLang.fields.name_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

resources/views/admin/countriesLangs/index.blade.php
@extends('layouts.admin')
@section('content')
@can('countries_lang_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.countries-langs.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.countriesLang.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.countriesLang.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-CountriesLang">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.language') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.country') }}
                        </th>
                        <th>
                            {{ trans('cruds.countriesLang.fields.name') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($countriesLangs as $key => $countriesLang)
                        <tr data-entry-id="{{ $countriesLang->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $countriesLang->id ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->language->name ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->country->name ?? '' }}
                            </td>
                            <td>
                                {{ $countriesLang->name ?? '' }}
                            </td>
                            <td>
                                @can('countries_lang_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.countries-langs.show', $countriesLang->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('countries_lang_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.countries-langs.edit', $countriesLang->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('countries_lang_delete')
                                    <form action="{{ route('admin.countries-langs.destroy', $countriesLang->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('countries_lang_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.countries-langs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-CountriesLang:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/countriesLangs/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.countriesLang.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.countries-langs.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.countriesLang.fields.id') }}
                        </th>
                        <td>
                            {{ $countriesLang->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.countriesLang.fields.language') }}
                        </th>
                        <td>
                            {{ $countriesLang->language->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.countriesLang.fields.country') }}
                        </th>
                        <td>
                            {{ $countriesLang->country->name ?? '' }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.countriesLang.fields.name') }}
                        </th>
                        <td>
                            {{ $countriesLang->name }}
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.countries-langs.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection