routes/web.php
<?php

use App\Http\Controllers\HomeController;

Route::get('/', [HomeController::class, 'main']);
Route::get('/home', [HomeController::class, 'main']);
Route::get('/tags/{id}', [HomeController::class, 'tags']);
Route::get('/category/{id}', [HomeController::class, 'category']);
Route::get('/page/{id}', [HomeController::class, 'page']);
Route::post('/save_comment', [HomeController::class, 'setComment']);
//Route::get('/contacts', [HomeController::class, 'contacts']);


Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth', 'admin']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    // Permissions
    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
    Route::resource('permissions', 'PermissionsController');

    // Roles
    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
    Route::resource('roles', 'RolesController');

    // Users
    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    // Content Category
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tag
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Page
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // Main Carousel
    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
    Route::resource('main-carousels', 'MainCarouselController');

    // Banks
    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
    Route::resource('banks', 'BanksController');

    // Banks Lang
    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
    Route::resource('banks-langs', 'BanksLangController');

    // Language
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // Countries Lang
    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
    Route::resource('countries-langs', 'CountriesLangController');

    // Ref Family Status
    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
    Route::resource('ref-family-statuses', 'RefFamilyStatusController');

    // Ref Family Status Lang
    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');

    // Nationality
    Route::delete('nationalities/destroy', 'NationalityController@massDestroy')->name('nationalities.massDestroy');
    Route::resource('nationalities', 'NationalityController');

    // Nationality Lang
    Route::delete('nationality-langs/destroy', 'NationalityLangController@massDestroy')->name('nationality-langs.massDestroy');
    Route::resource('nationality-langs', 'NationalityLangController');

    // Ref Oked
    Route::delete('ref-okeds/destroy', 'RefOkedController@massDestroy')->name('ref-okeds.massDestroy');
    Route::resource('ref-okeds', 'RefOkedController');

    // Ref Oked Lang
    Route::delete('ref-oked-langs/destroy', 'RefOkedLangController@massDestroy')->name('ref-oked-langs.massDestroy');
    Route::resource('ref-oked-langs', 'RefOkedLangController');

    // Ref Person State
    Route::delete('ref-person-states/destroy', 'RefPersonStateController@massDestroy')->name('ref-person-states.massDestroy');
    Route::resource('ref-person-states', 'RefPersonStateController');

    // Ref Person State Lang
    Route::delete('ref-person-state-langs/destroy', 'RefPersonStateLangController@massDestroy')->name('ref-person-state-langs.massDestroy');
    Route::resource('ref-person-state-langs', 'RefPersonStateLangController');

    // Ref Vacation Types
    Route::delete('ref-vacation-types/destroy', 'RefVacationTypesController@massDestroy')->name('ref-vacation-types.massDestroy');
    Route::resource('ref-vacation-types', 'RefVacationTypesController');

    // Ref Vacation Types Lang
    Route::delete('ref-vacation-types-langs/destroy', 'RefVacationTypesLangController@massDestroy')->name('ref-vacation-types-langs.massDestroy');
    Route::resource('ref-vacation-types-langs', 'RefVacationTypesLangController');

    // Comments
    Route::delete('comments/destroy', 'CommentsController@massDestroy')->name('comments.massDestroy');
    Route::resource('comments', 'CommentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::group(['as' => 'frontend.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
//    Route::get('/home', 'HomeController@index')->name('home');
//
//    // Permissions
//    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
//    Route::resource('permissions', 'PermissionsController');
//
//    // Roles
//    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
//    Route::resource('roles', 'RolesController');
//
//    // Users
//    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
//    Route::resource('users', 'UsersController');
//
//    // Content Category
//    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
//    Route::resource('content-categories', 'ContentCategoryController');
//
//    // Content Tag
//    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
//    Route::resource('content-tags', 'ContentTagController');
//
//    // Content Page
//    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
//    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
//    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
//    Route::resource('content-pages', 'ContentPageController');
//
//    // Main Carousel
//    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
//    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
//    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
//    Route::resource('main-carousels', 'MainCarouselController');
//
//    // Banks
//    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
//    Route::resource('banks', 'BanksController');
//
//    // Banks Lang
//    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
//    Route::resource('banks-langs', 'BanksLangController');
//
//    // Language
//    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
//    Route::resource('languages', 'LanguageController');
//
//    // Countries
//    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
//    Route::resource('countries', 'CountriesController');
//
//    // Countries Lang
//    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
//    Route::resource('countries-langs', 'CountriesLangController');
//
//    // Ref Family Status
//    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
//    Route::resource('ref-family-statuses', 'RefFamilyStatusController');
//
//    // Ref Family Status Lang
//    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
//    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');
//

app/Models/MainCarousel.php
<?php

namespace App\Models;

use DateTimeInterface;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

class MainCarousel extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia, HasFactory;

    public $table = 'main_carousels';

    protected $dates = [
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected $fillable = [
        'title',
        'body',
        'visible',
        'created_at',
        'updated_at',
        'deleted_at',
    ];

    protected function serializeDate(DateTimeInterface $date)
    {
        return $date->format('Y-m-d H:i:s');
    }

    public function registerMediaConversions(Media $media = null): void
    {
        $this->addMediaConversion('thumb')->fit('crop', 50, 50);
        $this->addMediaConversion('preview')->fit('crop', 120, 120);
    }
}

app/Http/Controllers/Admin/MainCarouselController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyMainCarouselRequest;
use App\Http\Requests\StoreMainCarouselRequest;
use App\Http\Requests\UpdateMainCarouselRequest;
use App\Models\MainCarousel;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class MainCarouselController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('main_carousel_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mainCarousels = MainCarousel::all();

        return view('admin.mainCarousels.index', compact('mainCarousels'));
    }

    public function create()
    {
        abort_if(Gate::denies('main_carousel_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.mainCarousels.create');
    }

    public function store(StoreMainCarouselRequest $request)
    {
        $mainCarousel = MainCarousel::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $mainCarousel->id]);
        }

        return redirect()->route('admin.main-carousels.index');
    }

    public function edit(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.mainCarousels.edit', compact('mainCarousel'));
    }

    public function update(UpdateMainCarouselRequest $request, MainCarousel $mainCarousel)
    {
        $mainCarousel->update($request->all());

        return redirect()->route('admin.main-carousels.index');
    }

    public function show(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('admin.mainCarousels.show', compact('mainCarousel'));
    }

    public function destroy(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mainCarousel->delete();

        return back();
    }

    public function massDestroy(MassDestroyMainCarouselRequest $request)
    {
        $mainCarousels = MainCarousel::find(request('ids'));

        foreach ($mainCarousels as $mainCarousel) {
            $mainCarousel->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('main_carousel_create') && Gate::denies('main_carousel_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new MainCarousel();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

app/Http/Controllers/Frontend/MainCarouselController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Controllers\Traits\MediaUploadingTrait;
use App\Http\Requests\MassDestroyMainCarouselRequest;
use App\Http\Requests\StoreMainCarouselRequest;
use App\Http\Requests\UpdateMainCarouselRequest;
use App\Models\MainCarousel;
use Gate;
use Illuminate\Http\Request;
use Spatie\MediaLibrary\MediaCollections\Models\Media;
use Symfony\Component\HttpFoundation\Response;

class MainCarouselController extends Controller
{
    use MediaUploadingTrait;

    public function index()
    {
        abort_if(Gate::denies('main_carousel_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mainCarousels = MainCarousel::all();

        return view('frontend.mainCarousels.index', compact('mainCarousels'));
    }

    public function create()
    {
        abort_if(Gate::denies('main_carousel_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.mainCarousels.create');
    }

    public function store(StoreMainCarouselRequest $request)
    {
        $mainCarousel = MainCarousel::create($request->all());

        if ($media = $request->input('ck-media', false)) {
            Media::whereIn('id', $media)->update(['model_id' => $mainCarousel->id]);
        }

        return redirect()->route('frontend.main-carousels.index');
    }

    public function edit(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.mainCarousels.edit', compact('mainCarousel'));
    }

    public function update(UpdateMainCarouselRequest $request, MainCarousel $mainCarousel)
    {
        $mainCarousel->update($request->all());

        return redirect()->route('frontend.main-carousels.index');
    }

    public function show(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.mainCarousels.show', compact('mainCarousel'));
    }

    public function destroy(MainCarousel $mainCarousel)
    {
        abort_if(Gate::denies('main_carousel_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $mainCarousel->delete();

        return back();
    }

    public function massDestroy(MassDestroyMainCarouselRequest $request)
    {
        $mainCarousels = MainCarousel::find(request('ids'));

        foreach ($mainCarousels as $mainCarousel) {
            $mainCarousel->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }

    public function storeCKEditorImages(Request $request)
    {
        abort_if(Gate::denies('main_carousel_create') && Gate::denies('main_carousel_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $model         = new MainCarousel();
        $model->id     = $request->input('crud_id', 0);
        $model->exists = true;
        $media         = $model->addMediaFromRequest('upload')->toMediaCollection('ck-media');

        return response()->json(['id' => $media->id, 'url' => $media->getUrl()], Response::HTTP_CREATED);
    }
}

resources/views/admin/mainCarousels/create.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.create') }} {{ trans('cruds.mainCarousel.title_singular') }}
    </div>

    <div class="card-body">
        <form method="POST" action="{{ route("admin.main-carousels.store") }}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="title">{{ trans('cruds.mainCarousel.fields.title') }}</label>
                <input class="form-control {{ $errors->has('title') ? 'is-invalid' : '' }}" type="text" name="title" id="title" value="{{ old('title', '') }}">
                @if($errors->has('title'))
                    <div class="invalid-feedback">
                        {{ $errors->first('title') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mainCarousel.fields.title_helper') }}</span>
            </div>
            <div class="form-group">
                <label for="body">{{ trans('cruds.mainCarousel.fields.body') }}</label>
                <textarea class="form-control ckeditor {{ $errors->has('body') ? 'is-invalid' : '' }}" name="body" id="body">{!! old('body') !!}</textarea>
                @if($errors->has('body'))
                    <div class="invalid-feedback">
                        {{ $errors->first('body') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mainCarousel.fields.body_helper') }}</span>
            </div>
            <div class="form-group">
                <div class="form-check {{ $errors->has('visible') ? 'is-invalid' : '' }}">
                    <input type="hidden" name="visible" value="0">
                    <input class="form-check-input" type="checkbox" name="visible" id="visible" value="1" {{ old('visible', 0) == 1 || old('visible') === null ? 'checked' : '' }}>
                    <label class="form-check-label" for="visible">{{ trans('cruds.mainCarousel.fields.visible') }}</label>
                </div>
                @if($errors->has('visible'))
                    <div class="invalid-feedback">
                        {{ $errors->first('visible') }}
                    </div>
                @endif
                <span class="help-block">{{ trans('cruds.mainCarousel.fields.visible_helper') }}</span>
            </div>
            <div class="form-group">
                <button class="btn btn-danger" type="submit">
                    {{ trans('global.save') }}
                </button>
            </div>
        </form>
    </div>
</div>



@endsection

@section('scripts')
<script>
    $(document).ready(function () {
  function SimpleUploadAdapter(editor) {
    editor.plugins.get('FileRepository').createUploadAdapter = function(loader) {
      return {
        upload: function() {
          return loader.file
            .then(function (file) {
              return new Promise(function(resolve, reject) {
                // Init request
                var xhr = new XMLHttpRequest();
                xhr.open('POST', '{{ route('admin.main-carousels.storeCKEditorImages') }}', true);
                xhr.setRequestHeader('x-csrf-token', window._token);
                xhr.setRequestHeader('Accept', 'application/json');
                xhr.responseType = 'json';

                // Init listeners
                var genericErrorText = `Couldn't upload file: ${ file.name }.`;
                xhr.addEventListener('error', function() { reject(genericErrorText) });
                xhr.addEventListener('abort', function() { reject() });
                xhr.addEventListener('load', function() {
                  var response = xhr.response;

                  if (!response || xhr.status !== 201) {
                    return reject(response && response.message ? `${genericErrorText}\n${xhr.status} ${response.message}` : `${genericErrorText}\n ${xhr.status} ${xhr.statusText}`);
                  }

                  $('form').append('<input type="hidden" name="ck-media[]" value="' + response.id + '">');

                  resolve({ default: response.url });
                });

                if (xhr.upload) {
                  xhr.upload.addEventListener('progress', function(e) {
                    if (e.lengthComputable) {
                      loader.uploadTotal = e.total;
                      loader.uploaded = e.loaded;
                    }
                  });
                }

                // Send request
                var data = new FormData();
                data.append('upload', file);
                data.append('crud_id', '{{ $mainCarousel->id ?? 0 }}');
                xhr.send(data);
              });
            })
        }
      };
    }
  }

  var allEditors = document.querySelectorAll('.ckeditor');
  for (var i = 0; i < allEditors.length; ++i) {
    ClassicEditor.create(
      allEditors[i], {
        extraPlugins: [SimpleUploadAdapter]
      }
    );
  }
});
</script>

@endsection

resources/views/admin/mainCarousels/index.blade.php
@extends('layouts.admin')
@section('content')
@can('main_carousel_create')
    <div style="margin-bottom: 10px;" class="row">
        <div class="col-lg-12">
            <a class="btn btn-success" href="{{ route('admin.main-carousels.create') }}">
                {{ trans('global.add') }} {{ trans('cruds.mainCarousel.title_singular') }}
            </a>
        </div>
    </div>
@endcan
<div class="card">
    <div class="card-header">
        {{ trans('cruds.mainCarousel.title_singular') }} {{ trans('global.list') }}
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class=" table table-bordered table-striped table-hover datatable datatable-MainCarousel">
                <thead>
                    <tr>
                        <th width="10">

                        </th>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.id') }}
                        </th>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.title') }}
                        </th>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.visible') }}
                        </th>
                        <th>
                            &nbsp;
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($mainCarousels as $key => $mainCarousel)
                        <tr data-entry-id="{{ $mainCarousel->id }}">
                            <td>

                            </td>
                            <td>
                                {{ $mainCarousel->id ?? '' }}
                            </td>
                            <td>
                                {{ $mainCarousel->title ?? '' }}
                            </td>
                            <td>
                                <span style="display:none">{{ $mainCarousel->visible ?? '' }}</span>
                                <input type="checkbox" disabled="disabled" {{ $mainCarousel->visible ? 'checked' : '' }}>
                            </td>
                            <td>
                                @can('main_carousel_show')
                                    <a class="btn btn-xs btn-primary" href="{{ route('admin.main-carousels.show', $mainCarousel->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('main_carousel_edit')
                                    <a class="btn btn-xs btn-info" href="{{ route('admin.main-carousels.edit', $mainCarousel->id) }}">
                                        {{ trans('global.edit') }}
                                    </a>
                                @endcan

                                @can('main_carousel_delete')
                                    <form action="{{ route('admin.main-carousels.destroy', $mainCarousel->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>

                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>



@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('main_carousel_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('admin.main-carousels.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-MainCarousel:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection

resources/views/admin/mainCarousels/show.blade.php
@extends('layouts.admin')
@section('content')

<div class="card">
    <div class="card-header">
        {{ trans('global.show') }} {{ trans('cruds.mainCarousel.title') }}
    </div>

    <div class="card-body">
        <div class="form-group">
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.main-carousels.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
            <table class="table table-bordered table-striped">
                <tbody>
                    <tr>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.id') }}
                        </th>
                        <td>
                            {{ $mainCarousel->id }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.title') }}
                        </th>
                        <td>
                            {{ $mainCarousel->title }}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.body') }}
                        </th>
                        <td>
                            {!! $mainCarousel->body !!}
                        </td>
                    </tr>
                    <tr>
                        <th>
                            {{ trans('cruds.mainCarousel.fields.visible') }}
                        </th>
                        <td>
                            <input type="checkbox" disabled="disabled" {{ $mainCarousel->visible ? 'checked' : '' }}>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="form-group">
                <a class="btn btn-default" href="{{ route('admin.main-carousels.index') }}">
                    {{ trans('global.back_to_list') }}
                </a>
            </div>
        </div>
    </div>
</div>



@endsection