routes/web.php
    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
    Route::resource('content-categories', 'ContentCategoryController');

    // Content Tag
    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
    Route::resource('content-tags', 'ContentTagController');

    // Content Page
    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
    Route::resource('content-pages', 'ContentPageController');

    // Main Carousel
    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
    Route::resource('main-carousels', 'MainCarouselController');

    // Banks
    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
    Route::resource('banks', 'BanksController');

    // Banks Lang
    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
    Route::resource('banks-langs', 'BanksLangController');

    // Language
    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
    Route::resource('languages', 'LanguageController');

    // Countries
    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
    Route::resource('countries', 'CountriesController');

    // Countries Lang
    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
    Route::resource('countries-langs', 'CountriesLangController');

    // Ref Family Status
    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
    Route::resource('ref-family-statuses', 'RefFamilyStatusController');

    // Ref Family Status Lang
    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');

    // Nationality
    Route::delete('nationalities/destroy', 'NationalityController@massDestroy')->name('nationalities.massDestroy');
    Route::resource('nationalities', 'NationalityController');

    // Nationality Lang
    Route::delete('nationality-langs/destroy', 'NationalityLangController@massDestroy')->name('nationality-langs.massDestroy');
    Route::resource('nationality-langs', 'NationalityLangController');

    // Ref Oked
    Route::delete('ref-okeds/destroy', 'RefOkedController@massDestroy')->name('ref-okeds.massDestroy');
    Route::resource('ref-okeds', 'RefOkedController');

    // Ref Oked Lang
    Route::delete('ref-oked-langs/destroy', 'RefOkedLangController@massDestroy')->name('ref-oked-langs.massDestroy');
    Route::resource('ref-oked-langs', 'RefOkedLangController');

    // Ref Person State
    Route::delete('ref-person-states/destroy', 'RefPersonStateController@massDestroy')->name('ref-person-states.massDestroy');
    Route::resource('ref-person-states', 'RefPersonStateController');

    // Ref Person State Lang
    Route::delete('ref-person-state-langs/destroy', 'RefPersonStateLangController@massDestroy')->name('ref-person-state-langs.massDestroy');
    Route::resource('ref-person-state-langs', 'RefPersonStateLangController');

    // Ref Vacation Types
    Route::delete('ref-vacation-types/destroy', 'RefVacationTypesController@massDestroy')->name('ref-vacation-types.massDestroy');
    Route::resource('ref-vacation-types', 'RefVacationTypesController');

    // Ref Vacation Types Lang
    Route::delete('ref-vacation-types-langs/destroy', 'RefVacationTypesLangController@massDestroy')->name('ref-vacation-types-langs.massDestroy');
    Route::resource('ref-vacation-types-langs', 'RefVacationTypesLangController');

    // Comments
    Route::delete('comments/destroy', 'CommentsController@massDestroy')->name('comments.massDestroy');
    Route::resource('comments', 'CommentsController');
});
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    // Change password
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
        Route::post('profile', 'ChangePasswordController@updateProfile')->name('password.updateProfile');
        Route::post('profile/destroy', 'ChangePasswordController@destroy')->name('password.destroyProfile');
    }
});
Route::group(['as' => 'frontend.', 'namespace' => 'Frontend', 'middleware' => ['auth']], function () {
//    Route::get('/home', 'HomeController@index')->name('home');
//
//    // Permissions
//    Route::delete('permissions/destroy', 'PermissionsController@massDestroy')->name('permissions.massDestroy');
//    Route::resource('permissions', 'PermissionsController');
//
//    // Roles
//    Route::delete('roles/destroy', 'RolesController@massDestroy')->name('roles.massDestroy');
//    Route::resource('roles', 'RolesController');
//
//    // Users
//    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
//    Route::resource('users', 'UsersController');
//
//    // Content Category
//    Route::delete('content-categories/destroy', 'ContentCategoryController@massDestroy')->name('content-categories.massDestroy');
//    Route::resource('content-categories', 'ContentCategoryController');
//
//    // Content Tag
//    Route::delete('content-tags/destroy', 'ContentTagController@massDestroy')->name('content-tags.massDestroy');
//    Route::resource('content-tags', 'ContentTagController');
//
//    // Content Page
//    Route::delete('content-pages/destroy', 'ContentPageController@massDestroy')->name('content-pages.massDestroy');
//    Route::post('content-pages/media', 'ContentPageController@storeMedia')->name('content-pages.storeMedia');
//    Route::post('content-pages/ckmedia', 'ContentPageController@storeCKEditorImages')->name('content-pages.storeCKEditorImages');
//    Route::resource('content-pages', 'ContentPageController');
//
//    // Main Carousel
//    Route::delete('main-carousels/destroy', 'MainCarouselController@massDestroy')->name('main-carousels.massDestroy');
//    Route::post('main-carousels/media', 'MainCarouselController@storeMedia')->name('main-carousels.storeMedia');
//    Route::post('main-carousels/ckmedia', 'MainCarouselController@storeCKEditorImages')->name('main-carousels.storeCKEditorImages');
//    Route::resource('main-carousels', 'MainCarouselController');
//
//    // Banks
//    Route::delete('banks/destroy', 'BanksController@massDestroy')->name('banks.massDestroy');
//    Route::resource('banks', 'BanksController');
//
//    // Banks Lang
//    Route::delete('banks-langs/destroy', 'BanksLangController@massDestroy')->name('banks-langs.massDestroy');
//    Route::resource('banks-langs', 'BanksLangController');
//
//    // Language
//    Route::delete('languages/destroy', 'LanguageController@massDestroy')->name('languages.massDestroy');
//    Route::resource('languages', 'LanguageController');
//
//    // Countries
//    Route::delete('countries/destroy', 'CountriesController@massDestroy')->name('countries.massDestroy');
//    Route::resource('countries', 'CountriesController');
//
//    // Countries Lang
//    Route::delete('countries-langs/destroy', 'CountriesLangController@massDestroy')->name('countries-langs.massDestroy');
//    Route::resource('countries-langs', 'CountriesLangController');
//
//    // Ref Family Status
//    Route::delete('ref-family-statuses/destroy', 'RefFamilyStatusController@massDestroy')->name('ref-family-statuses.massDestroy');
//    Route::resource('ref-family-statuses', 'RefFamilyStatusController');
//
//    // Ref Family Status Lang
//    Route::delete('ref-family-status-langs/destroy', 'RefFamilyStatusLangController@massDestroy')->name('ref-family-status-langs.massDestroy');
//    Route::resource('ref-family-status-langs', 'RefFamilyStatusLangController');
//
//    // Nationality
//    Route::delete('nationalities/destroy', 'NationalityController@massDestroy')->name('nationalities.massDestroy');
//    Route::resource('nationalities', 'NationalityController');
//
//    // Nationality Lang
//    Route::delete('nationality-langs/destroy', 'NationalityLangController@massDestroy')->name('nationality-langs.massDestroy');
//    Route::resource('nationality-langs', 'NationalityLangController');
//
//    // Ref Oked
//    Route::delete('ref-okeds/destroy', 'RefOkedController@massDestroy')->name('ref-okeds.massDestroy');
//    Route::resource('ref-okeds', 'RefOkedController');
//
//    // Ref Oked Lang
//    Route::delete('ref-oked-langs/destroy', 'RefOkedLangController@massDestroy')->name('ref-oked-langs.massDestroy');
//    Route::resource('ref-oked-langs', 'RefOkedLangController');
//
//    // Ref Person State
//    Route::delete('ref-person-states/destroy', 'RefPersonStateController@massDestroy')->name('ref-person-states.massDestroy');
//    Route::resource('ref-person-states', 'RefPersonStateController');
//
//    // Ref Person State Lang

app/Http/Controllers/Admin/RefOkedLangController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyRefOkedLangRequest;
use App\Http\Requests\StoreRefOkedLangRequest;
use App\Http\Requests\UpdateRefOkedLangRequest;
use App\Models\Language;
use App\Models\RefOked;
use App\Models\RefOkedLang;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class RefOkedLangController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('ref_oked_lang_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $refOkedLangs = RefOkedLang::with(['language', 'oked'])->get();

        return view('admin.refOkedLangs.index', compact('refOkedLangs'));
    }

    public function create()
    {
        abort_if(Gate::denies('ref_oked_lang_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $okeds = RefOked::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('admin.refOkedLangs.create', compact('languages', 'okeds'));
    }

    public function store(StoreRefOkedLangRequest $request)
    {
        $refOkedLang = RefOkedLang::create($request->all());

        return redirect()->route('admin.ref-oked-langs.index');
    }

    public function edit(RefOkedLang $refOkedLang)
    {
        abort_if(Gate::denies('ref_oked_lang_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $okeds = RefOked::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $refOkedLang->load('language', 'oked');

        return view('admin.refOkedLangs.edit', compact('languages', 'okeds', 'refOkedLang'));
    }

    public function update(UpdateRefOkedLangRequest $request, RefOkedLang $refOkedLang)
    {
        $refOkedLang->update($request->all());

        return redirect()->route('admin.ref-oked-langs.index');
    }

    public function show(RefOkedLang $refOkedLang)
    {
        abort_if(Gate::denies('ref_oked_lang_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $refOkedLang->load('language', 'oked');

        return view('admin.refOkedLangs.show', compact('refOkedLang'));
    }

    public function destroy(RefOkedLang $refOkedLang)
    {
        abort_if(Gate::denies('ref_oked_lang_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $refOkedLang->delete();

        return back();
    }

    public function massDestroy(MassDestroyRefOkedLangRequest $request)
    {
        $refOkedLangs = RefOkedLang::find(request('ids'));

        foreach ($refOkedLangs as $refOkedLang) {
            $refOkedLang->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/BanksController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyBankRequest;
use App\Http\Requests\StoreBankRequest;
use App\Http\Requests\UpdateBankRequest;
use App\Models\Bank;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BanksController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('bank_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $banks = Bank::all();

        return view('frontend.banks.index', compact('banks'));
    }

    public function create()
    {
        abort_if(Gate::denies('bank_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.banks.create');
    }

    public function store(StoreBankRequest $request)
    {
        $bank = Bank::create($request->all());

        return redirect()->route('frontend.banks.index');
    }

    public function edit(Bank $bank)
    {
        abort_if(Gate::denies('bank_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        return view('frontend.banks.edit', compact('bank'));
    }

    public function update(UpdateBankRequest $request, Bank $bank)
    {
        $bank->update($request->all());

        return redirect()->route('frontend.banks.index');
    }

    public function show(Bank $bank)
    {
        abort_if(Gate::denies('bank_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $bank->load('bankBanksLangs');

        return view('frontend.banks.show', compact('bank'));
    }

    public function destroy(Bank $bank)
    {
        abort_if(Gate::denies('bank_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $bank->delete();

        return back();
    }

    public function massDestroy(MassDestroyBankRequest $request)
    {
        $banks = Bank::find(request('ids'));

        foreach ($banks as $bank) {
            $bank->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/BanksLangController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Http\Controllers\Controller;
use App\Http\Requests\MassDestroyBanksLangRequest;
use App\Http\Requests\StoreBanksLangRequest;
use App\Http\Requests\UpdateBanksLangRequest;
use App\Models\Bank;
use App\Models\BanksLang;
use App\Models\Language;
use Gate;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BanksLangController extends Controller
{
    public function index()
    {
        abort_if(Gate::denies('banks_lang_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $banksLangs = BanksLang::with(['language', 'bank'])->get();

        return view('frontend.banksLangs.index', compact('banksLangs'));
    }

    public function create()
    {
        abort_if(Gate::denies('banks_lang_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $banks = Bank::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        return view('frontend.banksLangs.create', compact('banks', 'languages'));
    }

    public function store(StoreBanksLangRequest $request)
    {
        $banksLang = BanksLang::create($request->all());

        return redirect()->route('frontend.banks-langs.index');
    }

    public function edit(BanksLang $banksLang)
    {
        abort_if(Gate::denies('banks_lang_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $languages = Language::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $banks = Bank::pluck('name', 'id')->prepend(trans('global.pleaseSelect'), '');

        $banksLang->load('language', 'bank');

        return view('frontend.banksLangs.edit', compact('banks', 'banksLang', 'languages'));
    }

    public function update(UpdateBanksLangRequest $request, BanksLang $banksLang)
    {
        $banksLang->update($request->all());

        return redirect()->route('frontend.banks-langs.index');
    }

    public function show(BanksLang $banksLang)
    {
        abort_if(Gate::denies('banks_lang_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $banksLang->load('language', 'bank');

        return view('frontend.banksLangs.show', compact('banksLang'));
    }

    public function destroy(BanksLang $banksLang)
    {
        abort_if(Gate::denies('banks_lang_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $banksLang->delete();

        return back();
    }

    public function massDestroy(MassDestroyBanksLangRequest $request)
    {
        $banksLangs = BanksLang::find(request('ids'));

        foreach ($banksLangs as $banksLang) {
            $banksLang->delete();
        }

        return response(null, Response::HTTP_NO_CONTENT);
    }
}

app/Http/Controllers/Frontend/HomeController.php
<?php

namespace App\Http\Controllers\Frontend;

class HomeController
{
    public function index()
    {
        return view('frontend.home');
    }
}

resources/views/frontend/refOkedLangs/create.blade.php
@extends('layouts.frontend')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">

            <div class="card">
                <div class="card-header">
                    {{ trans('global.create') }} {{ trans('cruds.refOkedLang.title_singular') }}
                </div>

                <div class="card-body">
                    <form method="POST" action="{{ route("frontend.ref-oked-langs.store") }}" enctype="multipart/form-data">
                        @method('POST')
                        @csrf
                        <div class="form-group">
                            <label for="language_id">{{ trans('cruds.refOkedLang.fields.language') }}</label>
                            <select class="form-control select2" name="language_id" id="language_id">
                                @foreach($languages as $id => $entry)
                                    <option value="{{ $id }}" {{ old('language_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('language'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('language') }}
                                </div>
                            @endif
                            <span class="help-block">{{ trans('cruds.refOkedLang.fields.language_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <label for="oked_id">{{ trans('cruds.refOkedLang.fields.oked') }}</label>
                            <select class="form-control select2" name="oked_id" id="oked_id">
                                @foreach($okeds as $id => $entry)
                                    <option value="{{ $id }}" {{ old('oked_id') == $id ? 'selected' : '' }}>{{ $entry }}</option>
                                @endforeach
                            </select>
                            @if($errors->has('oked'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('oked') }}
                                </div>
                            @endif
                            <span class="help-block">{{ trans('cruds.refOkedLang.fields.oked_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <label for="name_oked">{{ trans('cruds.refOkedLang.fields.name_oked') }}</label>
                            <input class="form-control" type="text" name="name_oked" id="name_oked" value="{{ old('name_oked', '') }}">
                            @if($errors->has('name_oked'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('name_oked') }}
                                </div>
                            @endif
                            <span class="help-block">{{ trans('cruds.refOkedLang.fields.name_oked_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <label for="name">{{ trans('cruds.refOkedLang.fields.name') }}</label>
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name', '') }}">
                            @if($errors->has('name'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('name') }}
                                </div>
                            @endif
                            <span class="help-block">{{ trans('cruds.refOkedLang.fields.name_helper') }}</span>
                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger" type="submit">
                                {{ trans('global.save') }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection

resources/views/frontend/refOkedLangs/index.blade.php
@extends('layouts.frontend')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            @can('ref_oked_lang_create')
                <div style="margin-bottom: 10px;" class="row">
                    <div class="col-lg-12">
                        <a class="btn btn-success" href="{{ route('frontend.ref-oked-langs.create') }}">
                            {{ trans('global.add') }} {{ trans('cruds.refOkedLang.title_singular') }}
                        </a>
                    </div>
                </div>
            @endcan
            <div class="card">
                <div class="card-header">
                    {{ trans('cruds.refOkedLang.title_singular') }} {{ trans('global.list') }}
                </div>

                <div class="card-body">
                    <div class="table-responsive">
                        <table class=" table table-bordered table-striped table-hover datatable datatable-RefOkedLang">
                            <thead>
                                <tr>
                                    <th>
                                        {{ trans('cruds.refOkedLang.fields.id') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.refOkedLang.fields.language') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.refOkedLang.fields.oked') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.refOkedLang.fields.name_oked') }}
                                    </th>
                                    <th>
                                        {{ trans('cruds.refOkedLang.fields.name') }}
                                    </th>
                                    <th>
                                        &nbsp;
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($refOkedLangs as $key => $refOkedLang)
                                    <tr data-entry-id="{{ $refOkedLang->id }}">
                                        <td>
                                            {{ $refOkedLang->id ?? '' }}
                                        </td>
                                        <td>
                                            {{ $refOkedLang->language->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $refOkedLang->oked->name ?? '' }}
                                        </td>
                                        <td>
                                            {{ $refOkedLang->name_oked ?? '' }}
                                        </td>
                                        <td>
                                            {{ $refOkedLang->name ?? '' }}
                                        </td>
                                        <td>
                                            @can('ref_oked_lang_show')
                                                <a class="btn btn-xs btn-primary" href="{{ route('frontend.ref-oked-langs.show', $refOkedLang->id) }}">
                                                    {{ trans('global.view') }}
                                                </a>
                                            @endcan

                                            @can('ref_oked_lang_edit')
                                                <a class="btn btn-xs btn-info" href="{{ route('frontend.ref-oked-langs.edit', $refOkedLang->id) }}">
                                                    {{ trans('global.edit') }}
                                                </a>
                                            @endcan

                                            @can('ref_oked_lang_delete')
                                                <form action="{{ route('frontend.ref-oked-langs.destroy', $refOkedLang->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                                    <input type="submit" class="btn btn-xs btn-danger" value="{{ trans('global.delete') }}">
                                                </form>
                                            @endcan

                                        </td>

                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
@endsection
@section('scripts')
@parent
<script>
    $(function () {
  let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
@can('ref_oked_lang_delete')
  let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'
  let deleteButton = {
    text: deleteButtonTrans,
    url: "{{ route('frontend.ref-oked-langs.massDestroy') }}",
    className: 'btn-danger',
    action: function (e, dt, node, config) {
      var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {
          return $(entry).data('entry-id')
      });

      if (ids.length === 0) {
        alert('{{ trans('global.datatables.zero_selected') }}')

        return
      }

      if (confirm('{{ trans('global.areYouSure') }}')) {
        $.ajax({
          headers: {'x-csrf-token': _token},
          method: 'POST',
          url: config.url,
          data: { ids: ids, _method: 'DELETE' }})
          .done(function () { location.reload() })
      }
    }
  }
  dtButtons.push(deleteButton)
@endcan

  $.extend(true, $.fn.dataTable.defaults, {
    orderCellsTop: true,
    order: [[ 1, 'desc' ]],
    pageLength: 100,
  });
  let table = $('.datatable-RefOkedLang:not(.ajaxTable)').DataTable({ buttons: dtButtons })
  $('a[data-toggle="tab"]').on('shown.bs.tab click', function(e){
      $($.fn.dataTable.tables(true)).DataTable()
          .columns.adjust();
  });
  
})

</script>
@endsection